document.addEventListener('DOMContentLoaded', function() {
    const contentEn = document.getElementById('content-en');
    const contentRu = document.getElementById('content-ru');
    const ruBtn = document.getElementById('ru-btn');
    const enBtn = document.getElementById('en-btn');
    const markdownEn = document.getElementById('markdown-en');
    const markdownRu = document.getElementById('markdown-ru');
    const animatedText = document.getElementById('animated-text');

    const markdownContentEn = `# Plugin Publishing Rules
> Full free and open source software

## Malicious Code
**1.1** The plugin, including all its parts, must be open-source (fully without obfuscation or code confusion), or the source code must be provided for review during publication.  
**1.2** It must not contain any hidden actions or execute unknown arbitrary code (e.g., exec from GitHub).  
**1.3** It must not be linked to a private server without explicit disclosure and transparency of actions.  
**1.4** It must not collect personal data from plugin users without their knowledge / without disclosure during publication.  

## Content
**2.1** The plugin must not be obviously generated by AI; at least clean up the comments.  
**2.2** The plugin must not be an exact copy of an existing plugin / with minor modifications.  
**2.3** The plugin must be either completely free or fully paid (no premium/mixed models).  
**2.4** The plugin must not be useless or extremely narrowly applicable.  
**2.5** The plugin must not violate licenses or copyrights of other plugins.  

## Publication
**3.1** All dependencies (libraries) must be listed.  
**3.2** All external downloads not from a public API/server must be specified.  
**3.3** Any interactions with other plugins or incompatibilities must be stated.  
**3.4** When updating, it is advisable to include a list of changes in the update.
**3.5** If the plugin is a fork, it must be reported.
**3.6** If you wish, you can leave several links that will be added to the plugin publication.

To publish a plugin, use this:`;

    const markdownContentRu = `# Правила публикации плагинов
> Полностью бесплатное и открытое ПО

## Вредоносный код
**1.1** Плагин и все его части должны быть open-source (полностью без обфускации и запутывания кода), либо исходный код предоставляется для проверки при публикации.  
**1.2** Не должен содержать скрытых действий и выполнения неизвестного произвольного кода (например, exec с GitHub).  
**1.3** Не должен быть привязан к личному серверу без явного указания и прозрачности действий.  
**1.4** Не должен собирать персональные данные пользователей плагина без ведома пользователя / без указания при публикации.  

## Содержимое
**2.1** Плагин не должен быть явно написан нейросетью; хотя бы очистите комментарии.  
**2.2** Плагин не должен быть точной копией уже существующего плагина / с небольшим изменением.  
**2.3** Плагин должен быть полностью бесплатным или полностью платным (никаких premium/смешанных моделей).  
**2.4** Плагин не должен быть бесполезным или крайне узкоспециализированным.  
**2.5** Плагин не должен нарушать лицензии или авторские права других плагинов.  

## При публикации
**3.1** Необходимо указать все зависимости (библиотеки).  
**3.2** Необходимо указать все внешние загрузки, не с публичного API/сервера.  
**3.3** Необходимо указать взаимодействие с другими плагинами и возможные несовместимости.
**3.4** При обновлении желательно указать список изменений.
**3.5** Если плагин является форком, об этом нужно сообщить.
**3.6** По желанию, вы можете оставить несколько ссылок которые будут добавлены в публикацию плагина.

Что бы опубликовать плагин, воспользуйтесь этим:`;

    markdownEn.innerHTML = marked.parse(markdownContentEn);
    markdownRu.innerHTML = marked.parse(markdownContentRu);

    function showEnglish() {
        contentEn.classList.add('active');
        contentRu.classList.remove('active');
        enBtn.style.backgroundColor = '#333';
        ruBtn.style.backgroundColor = '#1a1a1a';
    }

    function showRussian() {
        contentRu.classList.add('active');
        contentEn.classList.remove('active');
        ruBtn.style.backgroundColor = '#333';
        enBtn.style.backgroundColor = '#1a1a1a';
    }

    enBtn.addEventListener('click', function() {
        contentEn.scrollIntoView({ behavior: 'smooth', block: 'start' });
        showEnglish();
    });

    ruBtn.addEventListener('click', function() {
        contentRu.scrollIntoView({ behavior: 'smooth', block: 'start' });
        showRussian();
    });

    showEnglish();

    const baseText = 'End of page';
    let dotsCount = 0;
    
    function animateDots() {
        dotsCount = (dotsCount + 1) % 4;
        const dots = '.'.repeat(dotsCount);
        animatedText.textContent = baseText + dots;
    }
    
    setInterval(animateDots, 500);
});
